### ISSUE TITLE
Plugin installs into the vendor folder, rather then plugins folder?

### ISSUE THREAD

**Issue by bvdputte** [getkirby/pluginkit#1]
First: I'm not sure this is the right place to ask for help? If it's not, you can sure point me into the right direction 😉

Problem:

My [fingerprint plugin](https://github.com/bvdputte/kirby-fingerprint) apparently installs into the vendor folder, rather then plugins folder when installing via composer? I followed the pluginkit best practices as close as possible and I'm clueless on how to solve this now (I'm not a composer user myself)?

Can you have a look at what I am doing wrong please? Thx!

**Comment by mauricerenck** [comment]
> I'm not sure this is the right place to ask for help? If it's not, you can sure point me into the right direction 😉

I think the forum is a better place to get an answer. There are a lot of peoply answering pretty fast: https://forum.getkirby.com/

**Comment by bvdputte** [comment]
I kinda agree, and then I don't 🙂

To me, following this boilerplate should enable you to set up a plugin that can be consumed by composer. I followed the steps, and I was unable to make it so. Unless I have made a mistake, I assume non-savvy-composer devs can encounter the same mistakes. In this respect, this _might_ belong here (too).

**Comment by lukasbestle** [comment]
You made a [change to your `composer.json` today](https://github.com/bvdputte/kirby-fingerprint/commit/d094fbd101916e4785416db5012306b77e673fbd) to add the `"type": "kirby-plugin"` line. This line is required, otherwise the installer won't run.

However your latest release (v2.1.0) does not include that change. Also, you have two Git tags (`v2.1.0` and `v.2.1.0`) for the same version. I'd suggest the following:

- Delete the duplicate `v.2.1.0` tag.
- Publish a new release `v2.1.1` based on the current state of the `master` branch.

**Comment by bvdputte** [comment]
You're right. It's even [in the docs](https://getkirby.com/docs/guide/plugins/plugin-setup-basic#the-composer-json).

Thx

**Comment by lukasbestle** [comment]
You are welcome. :)
